name: 'LD Data Validator'
description: 'Validate LD data before syncing'
inputs:
  commitCount:
    description: 'Number of commits in current push'
    required: true
  baseUrl:
    description: 'Base URL for syncing with the LD API'
    required: false
    default: 'https://app.launchdarkly.com'
outputs:
  commitCount:
    description: 'Number of commits in the push'
  event:
    description: 'The event that triggered the action'
  filesChanged:
    description: 'List of files changed in the push'
  flagsChanged:
    description: 'List of flags changed in the push'
  flagModifications:
    description: 'All flag modifications from this push'
runs:
  using: 'node16'
  main: 'dist/index.js'