name: 'LD Data Validator'
description: 'Validate LD data before syncing'
outputs:
  time:
    description: 'Time the action ran'
  event:
    description: 'The event that triggered the action'
  cwd:
    description: 'Current working directory of the process'
  contents:
    description: 'Contents of the current working directory'
runs:
  using: 'node16'
  main: 'dist/index.js'